// Liste generique de pays (noms en francais) pour le champ "Pays" d'une
// adresse structuree : volontairement une simple liste triee, sans logique
// specifique par pays, pour que l'adresse fonctionne de la meme facon
// partout dans le monde. "Etats-Unis" est place en tete (base de l'atelier).
export const COUNTRIES: string[] = [
  "Etats-Unis",
  "France",
  "Canada",
  "Royaume-Uni",
  "Allemagne",
  "Italie",
  "Espagne",
  "Suisse",
  "Belgique",
  "Pays-Bas",
  "Luxembourg",
  "Portugal",
  "Irlande",
  "Autriche",
  "Suede",
  "Norvege",
  "Danemark",
  "Finlande",
  "Pologne",
  "Republique tcheque",
  "Grece",
  "Hongrie",
  "Roumanie",
  "Bulgarie",
  "Croatie",
  "Slovenie",
  "Slovaquie",
  "Islande",
  "Monaco",
  "Andorre",
  "Malte",
  "Chypre",
  "Estonie",
  "Lettonie",
  "Lituanie",
  "Ukraine",
  "Russie",
  "Turquie",
  "Israel",
  "Emirats arabes unis",
  "Arabie saoudite",
  "Qatar",
  "Koweit",
  "Bahrein",
  "Oman",
  "Jordanie",
  "Liban",
  "Egypte",
  "Maroc",
  "Algerie",
  "Tunisie",
  "Afrique du Sud",
  "Nigeria",
  "Kenya",
  "Cote d'Ivoire",
  "Senegal",
  "Chine",
  "Japon",
  "Coree du Sud",
  "Hong Kong",
  "Taiwan",
  "Singapour",
  "Malaisie",
  "Thailande",
  "Vietnam",
  "Indonesie",
  "Philippines",
  "Inde",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "Australie",
  "Nouvelle-Zelande",
  "Mexique",
  "Bresil",
  "Argentine",
  "Chili",
  "Colombie",
  "Perou",
  "Uruguay",
  "Equateur",
  "Venezuela",
  "Panama",
  "Republique dominicaine",
  "Costa Rica",
  "Jamaique",
  "Bahamas",
  "Autre",
];
